# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages


r: bioc-devel

r_github_packages:
 - hadley/devtools#1263
 - rte-antares-rpackage/antares-rpackageRead@develop
 - rte-antares-rpackage/antaresProcessing@developTit
 - rte-antares-rpackage/manipulateWidget@develop
 - Bioconductor-mirror/zlibbioc
 - Bioconductor-mirror/rhdf5
 - rte-antares-rpackage/antaresHDF5 

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libv8-3.14-dev

include:
  - r: release
  - r: oldrel
  - r: devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'